### ISSUE TITLE
    raise RuntimeError("Invalid process group specified") RuntimeError: Invalid process group specified

### ISSUE THREAD

**Issue by simplecoderx** [Lornatang/YOLOv4-PyTorch#5]
When i'm trying to train the model with my custom datasets, it successfully produce weights but after training, it throws error.

PS C:\YOLOv4-PyTorch> python train.py --config-file configs/yolov3-custom.yaml --data data/custom.yaml --epochs 3  
Namespace(batch_size=16, cache_images=False, config_file='configs/yolov3-custom.yaml', data='data/custom.yaml', device='', epochs=3, image_size=640, resume=False, weights='')
Start Tensorboard with `tensorboard --logdir=runs`, view at http://localhost:6006/
Hyper parameters {'lr0': 0.01, 'momentum': 0.937, 'weight_decay': 0.0005, 'giou': 0.05, 'cls': 0.5, 'cls_pw': 1.0, 
'obj': 1.0, 'obj_pw': 1.0, 'iou_t': 0.2, 'anchor_t': 4.0, 'fl_gamma': 0.0, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'degrees': 0.0, 'translate': 0.0, 'scale': 0.5, 'shear': 0.0}
Using CUDA Apex
        + device:0 (name=`NVIDIA GeForce GTX 1060 6GB`, total_memory=6143MB)

                 from  n    params  module                                  arguments
  0                -1  1       928  yolov4_pytorch.model.module.conv.Conv   [3, 32, 3, 1]
  1                -1  1     18560  yolov4_pytorch.model.module.conv.Conv   [32, 64, 3, 2]
  2                -1  1     20672  yolov4_pytorch.model.module.neck.Bottleneck[64, 64]
  3                -1  1     73984  yolov4_pytorch.model.module.conv.Conv   [64, 128, 3, 2]
  4                -1  2    164608  yolov4_pytorch.model.module.neck.Bottleneck[128, 128]
  5                -1  1    295424  yolov4_pytorch.model.module.conv.Conv   [128, 256, 3, 2]
  6                -1  8   2627584  yolov4_pytorch.model.module.neck.Bottleneck[256, 256]
  7                -1  1   1180672  yolov4_pytorch.model.module.conv.Conv   [256, 512, 3, 2]
  8                -1  8  10498048  yolov4_pytorch.model.module.neck.Bottleneck[512, 512]
  9                -1  1   4720640  yolov4_pytorch.model.module.conv.Conv   [512, 1024, 3, 2]
 10                -1  4  20983808  yolov4_pytorch.model.module.neck.Bottleneck[1024, 1024]
 11                -1  3  15737856  yolov4_pytorch.model.module.neck.Bottleneck[1024, 1024, False]
 12                -1  1    262656  yolov4_pytorch.model.module.conv.Conv   [1024, 256, 1, 1]
 13                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 14           [-1, 8]  1         0  yolov4_pytorch.model.module.common.Concat[1]
 15                -1  1   1377792  yolov4_pytorch.model.module.neck.Bottleneck[768, 512, False]
 16                -1  2   2624512  yolov4_pytorch.model.module.neck.Bottleneck[512, 512, False]
 17                -1  1     65792  yolov4_pytorch.model.module.conv.Conv   [512, 128, 1, 1]
 18                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 19           [-1, 6]  1         0  yolov4_pytorch.model.module.common.Concat[1]
 20                -1  1    344832  yolov4_pytorch.model.module.neck.Bottleneck[384, 256, False]
 21                -1  2    656896  yolov4_pytorch.model.module.neck.Bottleneck[256, 256, False]
 22      [21, 16, 11]  1    183090  yolov4_pytorch.model.module.layer.Detect[29, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [256, 512, 1024]]
Model Summary: 222 layers, 6.18384e+07 parameters, 6.18384e+07 gradients

Optimizer groups: 75 .bias, 75 conv.weight, 72 other
Scanning labels ..\train\labels\train.cache (3 found, 0 missing, 0 empty, 0 duplicate, for 3 images): 100%|█| 3/3  
Scanning labels ..\train\labels\val.cache (3 found, 0 missing, 0 empty, 0 duplicate, for 3 images): 100%|█| 3/3 [0 

Analyzing anchors... Best Possible Recall (BPR) = 1.0000
Image sizes 640 train, 640 test
Using 8 dataloader workers
Starting training for 3 epochs...

     Epoch    memory      GIoU       obj       cls     total   targets image size
     0/2      2.3G    0.1331    0.0552    0.0858    0.2740        39       640: 100%|█| 1/1 [00:04<00:00,  4.96s/i
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|█| 1/1 [00:03<0
                 all           3         0.0       0.000       0.000       0.000       0.000

     Epoch    memory      GIoU       obj       cls     total   targets image size
     1/2      2.6G    0.1252    0.0611    0.0851    0.2714        35       640: 100%|█| 1/1 [00:04<00:00,  4.37s/i
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|█| 1/1 [00:03<0
                 all           3         0.0       0.000       0.000       0.000       0.000

     Epoch    memory      GIoU       obj       cls     total   targets image size
     2/2      2.7G    0.1203    0.0561    0.0835    0.2598        25       640: 100%|█| 1/1 [00:04<00:00,  4.23s/i
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|█| 1/1 [00:03<0
                 all           3         0.0       0.000       0.000       0.000       0.000
2 epochs completed in 0.008 hours.

Traceback (most recent call last):
  File "train.py", line 324, in <module>
    train()
  File "train.py", line 289, in train
    torch.distributed.destroy_process_group()
  File "C:\Users\ai-traffic\.conda\envs\yolov3-sample-c\lib\site-packages\torch\distributed\distributed_c10d.py", line 573, in destroy_process_group
    raise RuntimeError("Invalid process group specified")
RuntimeError: Invalid process group specified

Can someone help me fix this? I'm new in object detection.

**Comment by Haniaaliii** [comment]
Hi @simplecoderx, did the model work with you ? 

Thank you in advance !
